# dynaprot_simple.yaml

# Model training and testing settings
model_params:
  num_ipa_blocks: 8
  d_model: 128
  readout_hidden_dim: 128
  readout_layers: 4
  readout_rank: 16
  readout_dropout: 0.1
  use_layernorm: False
  pair_divisor: 2
  pair_heads: 4
  pair_dim_head: 16
  pair_blocks: 1

train_params:
  precision: 64
  batch_size: 1
  epochs: 10000
  learning_rate: 0.0001
  warmup_steps: 2000
  total_steps: 20000
  grad_clip_norm: 1.0
  accelerator: "gpu"
  strategy: "ddp"
  accumulate_grad_batches: 5
  num_devices: [0,1,2,3,4,5,6,7]
  num_nodes: 1
  project: "openprot/dynamics"
  neptune_api_key: "INSERT YOUR API TOKEN HERE"
  tags: ["dynaprot", "debugging"]
  log_model_checkpoints: True

  out_type: "joint_pairattention"

eval_params:    
  loss_weights:  # hyperparameters for loss functions per dynamics readout, if null/0.0 then loss is not used (0.0 will still log the loss)
    resi_gaussians:
      mse_means: 0.0
      mse_covs: 0.0
      kldiv: 0.0
      eigen_penalty: null
      cond_penalty: null
      frob_norm: 0.0
      log_frob_norm: 0.0
      affine_invariant_dist: 0.0
      bures_dist: 0.0
      mse_diag: 0.0

    resi_rmsf:
      corr_sp: 0.0
      corr_pcc: 0.0

    resi_correlations:
      mse: 0.0
      bures_dist: null
      log_frob_norm: 1.0
      
    resi_rmsd: null
    resi_rg: null

# Output paths for model artifacts and logs

# checkpoint_path: "/data/cb/mihirb14/projects/dynaprot/.neptune/DYNAMICS-131/DYNAMICS-131/checkpoints/epoch=5934-step=65285.ckpt"
checkpoint_path: ""
logs: "/path/to/logs"
results: "/path/to/results"
 
