# dynaprot_simple.yaml

# Model training and testing settings
model_params:
  num_ipa_blocks: 8
  d_model: 128

train_params:
  precision: 32
  batch_size: 20
  epochs: 10000
  learning_rate: 0.0001
  grad_clip_norm: 1.0
  accelerator: "gpu"
  strategy: "ddp"
  num_devices: [2,3,4,5,6]
  num_nodes: 1
  project: "openprot/dynamics"
  neptune_api_key: "INSERT YOUR API TOKEN HERE"
  tags: ["dynaprot", "debugging"]
  log_model_checkpoints: True

eval_params:    
  loss_weights:  # hyperparameters for loss functions per dynamics readout, if null/0.0 then loss is not used (0.0 will still log the loss)
    resi_gaussians:
      mse_means: 0.0
      mse_covs: 0.0
      kldiv: 0.0
      eigen_penalty: 0.0
      cond_penalty: 0.0
      frob_norm: 0.0
      log_frob_norm: 0.0
      affine_invariant_dist: 0.0
      bures_dist: 1.0
    resi_rmsf: null
    resi_rmsd: null
    resi_rg: null

# Output paths for model artifacts and logs

# checkpoint_path: "/data/cb/mihirb14/projects/dynaprot/.neptune/DYNAMICS-131/DYNAMICS-131/checkpoints/epoch=5934-step=65285.ckpt"
checkpoint_path: ""
logs: "/path/to/logs"
results: "/path/to/results"
 
